/**
 * Audit Logs seed data
 * 20 audit log records covering major entity types and actions
 */

import { auditLogs } from '@equipment-management/db/schema';
import { daysAgo, addHours } from '../../utils/date-helpers';
import {
  EQUIP_SPECTRUM_ANALYZER_SUW_E_ID,
  EQUIP_SIGNAL_GEN_SUW_E_ID,
  EQUIP_POWER_METER_SUW_E_ID,
  EQUIP_NETWORK_ANALYZER_SUW_E_ID,
  EQUIP_RECEIVER_UIW_W_ID,
  EQUIP_EMC32_SUW_P_ID,
  CALIB_001_ID,
  CALIB_002_ID,
  NC_001_ID,
  NC_006_ID,
  REPAIR_001_ID,
  USER_TEST_ENGINEER_SUWON_ID,
  USER_TECHNICAL_MANAGER_SUWON_ID,
  USER_LAB_MANAGER_SUWON_ID,
  USER_QUALITY_MANAGER_SUWON_ID,
  USER_TEST_ENGINEER_UIWANG_ID,
  USER_TECHNICAL_MANAGER_UIWANG_ID,
  TEAM_FCC_EMC_RF_SUWON_ID,
  TEAM_GENERAL_RF_UIWANG_ID,
  SOFT_HIST_001_ID,
} from '../../utils/uuid-constants';

export const AUDIT_LOGS_SEED_DATA: (typeof auditLogs.$inferInsert)[] = [
  // Equipment actions
  {
    timestamp: addHours(daysAgo(90), 9),
    userId: USER_TEST_ENGINEER_SUWON_ID,
    userName: '김시험',
    userRole: 'test_engineer',
    action: 'create',
    entityType: 'equipment',
    entityId: EQUIP_SPECTRUM_ANALYZER_SUW_E_ID,
    entityName: '스펙트럼 분석기 (SUW-E0001)',
    details: { newValue: { name: '스펙트럼 분석기', site: 'SUW', classification: 'E' } },
    ipAddress: '192.168.1.100',
    userSite: 'SUW',
    userTeamId: TEAM_FCC_EMC_RF_SUWON_ID,
  },
  {
    timestamp: addHours(daysAgo(85), 10),
    userId: USER_TECHNICAL_MANAGER_SUWON_ID,
    userName: '박기술',
    userRole: 'technical_manager',
    action: 'approve',
    entityType: 'equipment',
    entityId: EQUIP_SPECTRUM_ANALYZER_SUW_E_ID,
    entityName: '스펙트럼 분석기 (SUW-E0001)',
    details: { additionalInfo: { action: 'equipment_registration_approved' } },
    ipAddress: '192.168.1.101',
    userSite: 'SUW',
    userTeamId: TEAM_FCC_EMC_RF_SUWON_ID,
  },
  {
    timestamp: addHours(daysAgo(80), 14),
    userId: USER_TEST_ENGINEER_SUWON_ID,
    userName: '김시험',
    userRole: 'test_engineer',
    action: 'update',
    entityType: 'equipment',
    entityId: EQUIP_SIGNAL_GEN_SUW_E_ID,
    entityName: '신호 발생기 (SUW-E0002)',
    details: {
      previousValue: { location: '수원 본관 1층 입고실' },
      newValue: { location: '수원 본관 2층 EMC 시험실 A' },
    },
    ipAddress: '192.168.1.100',
    userSite: 'SUW',
    userTeamId: TEAM_FCC_EMC_RF_SUWON_ID,
  },

  // Calibration actions
  {
    timestamp: addHours(daysAgo(60), 9),
    userId: USER_TEST_ENGINEER_SUWON_ID,
    userName: '김시험',
    userRole: 'test_engineer',
    action: 'create',
    entityType: 'calibration',
    entityId: CALIB_001_ID,
    entityName: '스펙트럼 분석기 교정 (2026-01)',
    details: { newValue: { calibrationType: 'external', provider: 'KOLAS 인증 기관' } },
    ipAddress: '192.168.1.100',
    userSite: 'SUW',
    userTeamId: TEAM_FCC_EMC_RF_SUWON_ID,
  },
  {
    timestamp: addHours(daysAgo(58), 11),
    userId: USER_TECHNICAL_MANAGER_SUWON_ID,
    userName: '박기술',
    userRole: 'technical_manager',
    action: 'approve',
    entityType: 'calibration',
    entityId: CALIB_001_ID,
    entityName: '스펙트럼 분석기 교정 (2026-01)',
    details: { additionalInfo: { comment: '교정 성적서 확인 완료' } },
    ipAddress: '192.168.1.101',
    userSite: 'SUW',
    userTeamId: TEAM_FCC_EMC_RF_SUWON_ID,
  },
  {
    timestamp: addHours(daysAgo(55), 15),
    userId: USER_TECHNICAL_MANAGER_SUWON_ID,
    userName: '박기술',
    userRole: 'technical_manager',
    action: 'reject',
    entityType: 'calibration',
    entityId: CALIB_002_ID,
    entityName: '신호 발생기 교정 (2026-01)',
    details: { additionalInfo: { reason: '교정 성적서 누락' } },
    ipAddress: '192.168.1.101',
    userSite: 'SUW',
    userTeamId: TEAM_FCC_EMC_RF_SUWON_ID,
  },

  // Checkout actions
  {
    timestamp: addHours(daysAgo(40), 9),
    userId: USER_TEST_ENGINEER_SUWON_ID,
    userName: '김시험',
    userRole: 'test_engineer',
    action: 'checkout',
    entityType: 'checkout',
    entityId: EQUIP_NETWORK_ANALYZER_SUW_E_ID,
    entityName: '네트워크 분석기 반출',
    details: { additionalInfo: { purpose: '외부 교정', expectedReturn: '2026-03-01' } },
    ipAddress: '192.168.1.100',
    userSite: 'SUW',
    userTeamId: TEAM_FCC_EMC_RF_SUWON_ID,
  },
  {
    timestamp: addHours(daysAgo(35), 16),
    userId: USER_TEST_ENGINEER_SUWON_ID,
    userName: '김시험',
    userRole: 'test_engineer',
    action: 'return',
    entityType: 'checkout',
    entityId: EQUIP_NETWORK_ANALYZER_SUW_E_ID,
    entityName: '네트워크 분석기 반입',
    details: { additionalInfo: { condition: 'normal' } },
    ipAddress: '192.168.1.100',
    userSite: 'SUW',
    userTeamId: TEAM_FCC_EMC_RF_SUWON_ID,
  },

  // Non-conformance actions
  {
    timestamp: addHours(daysAgo(30), 10),
    userId: USER_TEST_ENGINEER_SUWON_ID,
    userName: '김시험',
    userRole: 'test_engineer',
    action: 'create',
    entityType: 'non_conformance',
    entityId: NC_001_ID,
    entityName: '파워미터 부적합 보고',
    details: { newValue: { equipmentId: EQUIP_POWER_METER_SUW_E_ID, type: 'measurement_error' } },
    ipAddress: '192.168.1.100',
    userSite: 'SUW',
    userTeamId: TEAM_FCC_EMC_RF_SUWON_ID,
  },
  {
    timestamp: addHours(daysAgo(28), 11),
    userId: USER_TECHNICAL_MANAGER_SUWON_ID,
    userName: '박기술',
    userRole: 'technical_manager',
    action: 'approve',
    entityType: 'non_conformance',
    entityId: NC_001_ID,
    entityName: '파워미터 부적합 보고',
    details: { additionalInfo: { correctionPlan: '센서 헤드 교체 후 재교정' } },
    ipAddress: '192.168.1.101',
    userSite: 'SUW',
    userTeamId: TEAM_FCC_EMC_RF_SUWON_ID,
  },
  {
    timestamp: addHours(daysAgo(10), 14),
    userId: USER_TECHNICAL_MANAGER_SUWON_ID,
    userName: '박기술',
    userRole: 'technical_manager',
    action: 'close',
    entityType: 'non_conformance',
    entityId: NC_006_ID,
    entityName: '하네스 커플러 부적합 종결',
    details: { additionalInfo: { resolution: '수리 완료, 재교정 통과' } },
    ipAddress: '192.168.1.101',
    userSite: 'SUW',
    userTeamId: TEAM_FCC_EMC_RF_SUWON_ID,
  },

  // Repair history
  {
    timestamp: addHours(daysAgo(10), 9),
    userId: USER_TECHNICAL_MANAGER_SUWON_ID,
    userName: '박기술',
    userRole: 'technical_manager',
    action: 'create',
    entityType: 'repair_history',
    entityId: REPAIR_001_ID,
    entityName: '하네스 커플러 수리 기록',
    details: { newValue: { result: 'completed', provider: '케이사이트 서비스센터' } },
    ipAddress: '192.168.1.101',
    userSite: 'SUW',
    userTeamId: TEAM_FCC_EMC_RF_SUWON_ID,
  },

  // Software actions
  {
    timestamp: addHours(daysAgo(180), 10),
    userId: USER_TEST_ENGINEER_SUWON_ID,
    userName: '김시험',
    userRole: 'test_engineer',
    action: 'create',
    entityType: 'software',
    entityId: SOFT_HIST_001_ID,
    entityName: 'EMC32 v10.0.0 설치',
    details: { newValue: { softwareName: 'EMC32', version: '10.0.0' } },
    ipAddress: '192.168.1.100',
    userSite: 'SUW',
    userTeamId: TEAM_FCC_EMC_RF_SUWON_ID,
  },
  {
    timestamp: addHours(daysAgo(179), 14),
    userId: USER_TECHNICAL_MANAGER_SUWON_ID,
    userName: '박기술',
    userRole: 'technical_manager',
    action: 'approve',
    entityType: 'software',
    entityId: SOFT_HIST_001_ID,
    entityName: 'EMC32 v10.0.0 설치 승인',
    details: { additionalInfo: { comment: '설치 확인 완료' } },
    ipAddress: '192.168.1.101',
    userSite: 'SUW',
    userTeamId: TEAM_FCC_EMC_RF_SUWON_ID,
  },

  // Auth actions
  {
    timestamp: addHours(daysAgo(1), 8),
    userId: USER_TEST_ENGINEER_SUWON_ID,
    userName: '김시험',
    userRole: 'test_engineer',
    action: 'login',
    entityType: 'user',
    entityId: USER_TEST_ENGINEER_SUWON_ID,
    entityName: '김시험',
    details: { additionalInfo: { method: 'azure_ad' } },
    ipAddress: '192.168.1.100',
    userSite: 'SUW',
    userTeamId: TEAM_FCC_EMC_RF_SUWON_ID,
  },
  {
    timestamp: addHours(daysAgo(1), 18),
    userId: USER_TEST_ENGINEER_SUWON_ID,
    userName: '김시험',
    userRole: 'test_engineer',
    action: 'logout',
    entityType: 'user',
    entityId: USER_TEST_ENGINEER_SUWON_ID,
    entityName: '김시험',
    ipAddress: '192.168.1.100',
    userSite: 'SUW',
    userTeamId: TEAM_FCC_EMC_RF_SUWON_ID,
  },
  {
    timestamp: addHours(daysAgo(2), 9),
    userId: USER_LAB_MANAGER_SUWON_ID,
    userName: '이시험소장',
    userRole: 'lab_manager',
    action: 'login',
    entityType: 'user',
    entityId: USER_LAB_MANAGER_SUWON_ID,
    entityName: '이시험소장',
    details: { additionalInfo: { method: 'azure_ad' } },
    ipAddress: '192.168.1.102',
    userSite: 'SUW',
    userTeamId: TEAM_FCC_EMC_RF_SUWON_ID,
  },
  {
    timestamp: addHours(daysAgo(3), 10),
    userId: USER_QUALITY_MANAGER_SUWON_ID,
    userName: '최품질',
    userRole: 'quality_manager',
    action: 'login',
    entityType: 'user',
    entityId: USER_QUALITY_MANAGER_SUWON_ID,
    entityName: '최품질',
    details: { additionalInfo: { method: 'azure_ad' } },
    ipAddress: '192.168.1.103',
    userSite: 'SUW',
    userTeamId: TEAM_FCC_EMC_RF_SUWON_ID,
  },

  // Uiwang site actions
  {
    timestamp: addHours(daysAgo(60), 9),
    userId: USER_TEST_ENGINEER_UIWANG_ID,
    userName: '정시험(의왕)',
    userRole: 'test_engineer',
    action: 'create',
    entityType: 'equipment',
    entityId: EQUIP_RECEIVER_UIW_W_ID,
    entityName: 'RF 수신기 (UIW-W0001)',
    details: { newValue: { name: 'RF 수신기', site: 'UIW', classification: 'W' } },
    ipAddress: '192.168.2.100',
    userSite: 'UIW',
    userTeamId: TEAM_GENERAL_RF_UIWANG_ID,
  },
  {
    timestamp: addHours(daysAgo(59), 14),
    userId: USER_TECHNICAL_MANAGER_UIWANG_ID,
    userName: '한기술(의왕)',
    userRole: 'technical_manager',
    action: 'approve',
    entityType: 'equipment',
    entityId: EQUIP_RECEIVER_UIW_W_ID,
    entityName: 'RF 수신기 (UIW-W0001)',
    details: { additionalInfo: { action: 'equipment_registration_approved' } },
    ipAddress: '192.168.2.101',
    userSite: 'UIW',
    userTeamId: TEAM_GENERAL_RF_UIWANG_ID,
  },
];
