#ENC[AES256_GCM,data:lBcqWeeUGDz4EBkIqnZSLbT7V+aUKrVZ/NzxqmLDJYCMkSAl9DZilpxzqJ2D0Eb+,iv:MaKlTpFJZtnR7njvy0RTNRLvyCrzr37ATFp3c6hl9mU=,tag:rfA5p+rrK2N0wnO50VHLOw==,type:comment]
#ENC[AES256_GCM,data:CXkgDEuNGZOvjdwG3ugPSaSoEgFWnfVTM2X10wLvcbgoZGvmijI6HTDvyBU2Tvqw/Njo+4NKktqw+XdL5TEjw1HRZvgnbGRJ0BCx,iv:aFMXyVdmE0NSt3srSv12O+yngL8r+QgAR58AiEklpgc=,tag:nCt3MKHcdM2F2koO9A5/yg==,type:comment]
#ENC[AES256_GCM,data:PnbiYJTK8iWlLjg7NIlJrUa7iqU+i4JXrMOH+sFR0vRH86meRoCwKe7d8ilvV23KffnN+BP1ApN4XgEQkA==,iv:6QoQyqDiRHtUNEGQdZtn67Gu5LSrEYiJUcHU/IgrsGw=,tag:c4fouWRUdHXU+98cF7XoAA==,type:comment]
#ENC[AES256_GCM,data:vKkL8atQG1jlYKU=,iv:z0ubryHc+S/SeMkEOqph2DTcR2riaGRgHS3IIRlqW0A=,tag:sm0GK7OMlkNvoB1UnoMiGw==,type:comment]
DB_PASSWORD: ENC[AES256_GCM,data:3neB6xFbVMimhHVcltrriTaU6APzCetuTW+Qa7+I3A==,iv:9/SOuNpgI88ZpoAPKq0jFHQz8tYZt4LBqxlfRnfPS5s=,tag:3B0OIIGUJ4rgbWzxR9oYSw==,type:str]
DB_NAME: ENC[AES256_GCM,data:xIw6WnccNf+iAReb4D1pSZ8G,iv:S8Hfb6cCfaZzTrPtE78vOyvsWgcVECk9Tcz1ESrAWQk=,tag:L2wwBAu3GO4/CteWKL65mA==,type:str]
#ENC[AES256_GCM,data:sA/zqL07,iv:xhJMqODPR8UCbMU/lyQazYhkwQVdqyVamvc4IimJo1c=,tag:leU78LwBUllxb1siiRDjBg==,type:comment]
REDIS_PASSWORD: ENC[AES256_GCM,data:LKuaaLq1t5YG72pGtjdRz89dKL8Zuavo+C6vYg==,iv:b1duj2IYNlyj8UoS+NsTOmMlmHtn1GIcLbLjkbyKsJ8=,tag:905vmfIMHGFn8yfBDCzJug==,type:str]
#ENC[AES256_GCM,data:ehY/NrUcjjI3IrRvUQ==,iv:KfjcEPFrN7XgWPQhT00i43pKVBXcjFSzhgTfVOLrPXg=,tag:vkXPP34lothLgWukJjxAlw==,type:comment]
JWT_SECRET: ENC[AES256_GCM,data:346mcbtjeDitdDVolT5JK+yVaORjGX+3PiiA+r385e+/70Vw580+I0gfkRI=,iv:WHKtEeducDPYoaAG16eXIT5sBHOzYQHXz+B9qo6mh2s=,tag:DR2qU7C1dlndO5FLB1IqcA==,type:str]
REFRESH_TOKEN_SECRET: ENC[AES256_GCM,data:HdWOAyXDPoTo7zL54FQC8OLNa7rcAVLuY/+AVm3LnkrOOIdwHe+KFds=,iv:h7wGf0lTJXRhsVLSurl285HFQ7sjmvZdSIf4/hMZ3qc=,tag:CsHYWDJqXzO+ZffMBivrdQ==,type:str]
INTERNAL_API_KEY: ENC[AES256_GCM,data:PWfm0UgYMDhh84M9GNOYHSgG91cvG3r+duFO71yy,iv:2CKD636tUXkaQ/Zv5TBSkNuHAvV6qSUmPg840PS3bE4=,tag:pyGY9BMIjrl4/NWJ61k46A==,type:str]
NEXTAUTH_SECRET: ENC[AES256_GCM,data:AsJbKZTUS3BupaBR+Sds3/Ks2aKcA7EutBhVWzc=,iv:02w2rVswBOF8y7s+s404P/Pu94fwzAuajl9vGntgx+Q=,tag:DpjInvEOBtlKasoCYgHH2Q==,type:str]
#ENC[AES256_GCM,data:lG8aKesAiV9J,iv:XL3Wzd1CspsI6ZSaZmOr/8U37lA68MXWNGrCpRNuyXc=,tag:PoXMuk4UkuK71YOh4cjN8w==,type:comment]
AZURE_AD_CLIENT_ID: ENC[AES256_GCM,data:Ypf0upRFHFT0C4PxZdn1nNwfGAGN6f1pMw==,iv:RKVj0kb1eMJHwads24xRzqThvr2VCn0t4htLDGcVdsk=,tag:/SkxGVMrm/YTnDu33wL9BQ==,type:str]
AZURE_AD_CLIENT_SECRET: ENC[AES256_GCM,data:3KsfLh870z8i4pFqS6RtCYHdZ8qFwrGtIupBrrM=,iv:iE9dKk+JHVJf0R0eQkn7RXRESSBMoeas8HBTCIqOGDI=,tag:AMZnwO4wCHMoeFACYPBC1Q==,type:str]
AZURE_AD_TENANT_ID: ENC[AES256_GCM,data:bM8c7EBxanOPUZo9so9QFdc5d0Wv57x9JA==,iv:ZwxPVl8pMCXVVIqc1Tbmu+fyHK3jcsRyZ/Aq4F2V8ek=,tag:kMuD1HswovyEz9lHgUQp8w==,type:str]
#ENC[AES256_GCM,data:J2k94EaFozQHPFuh,iv:9d1g9e7EZIIAyT7F0E6nhPwdVLcKB5z22ZTJkOOYiok=,tag:kkIlyIMUHAMxbIjmtgGZEg==,type:comment]
S3_ACCESS_KEY: ENC[AES256_GCM,data:dZhBr5ekFrLGyk4nJZJ9lbjfd47hZn4GSkBx,iv:GPkCLMiSfjBFPm+5TkUJE8n/oj5NEstTU+xVt5S+Pr4=,tag:T5M2wEUr16SbP8eTkOYbbg==,type:str]
S3_SECRET_KEY: ENC[AES256_GCM,data:lcucTVD30AQezR7d8uEFDU/sUYnjyF+YmTRt,iv:jgdxSfpEfB15+Pp227i18voDJBzecHmiu6suMYmVwho=,tag:0VDrbh10EHj4tAE2fbg1xQ==,type:str]
S3_BUCKET: ENC[AES256_GCM,data:VRTS7PvbAy1EHths2rhA,iv:EMjXfCxUGkkeY2t2R6SBJKfyMIQWeEzMNIovB399k1w=,tag:QLxBgAnicSlqQsJmD04wtg==,type:str]
#ENC[AES256_GCM,data:DcYGyzrRS+5B1TZGclI=,iv:meLsIbSzY8m83kSfBE3GmpnQwsl7sp2K3WX3Hm3R26M=,tag:vVvizHSuIrYd8eQ2OBcQpQ==,type:comment]
SERVER_LAN_IP: ENC[AES256_GCM,data:RB1mRzUwoB/TuB9D0A==,iv:gtf5S38jCEOQC2hratYbZIgCg9WOjmF7I0u6p/Oj820=,tag:/LSunFgsvdvRvB4V7jGM/A==,type:str]
LOG_LEVEL: ENC[AES256_GCM,data:yQtNkQ==,iv:+IpUPRxkUJSnvIY+8YwVmovNv2sFV5steW2ix0hRCiU=,tag:VzzRS0tpyx5TqJaiE8h4nw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1ts2rpha0f7rjlslevf62t604q2gh7s68mt90h6lg70250pr4w59qzzk5tc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHa0hrWTZTeU5Ya0VVZTJV
        eTZnQlJqakJKMXpzUkpBczRBNzJIOHBoa3g0CkR6VEw1SHdzYmQyeXZBdmYyekcx
        QjRJZDU0VlhtOVMvTkxJQnJmVWgyVXcKLS0tIHJVcXVlQUM1Mm9JZklQTGdJMWxH
        eWptUkFNcldJMTNWaDFuNEhkZDNkS0UKBr2JGWsuFn29TClbZttYK2SCsgG6gNGs
        ystv97+wfu6E91Asu83vsDLnKh0cLmiZOiWCL1bYckIJL2Lm8VDfWA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: '2026-04-15T07:52:52Z'
  mac: ENC[AES256_GCM,data:avq+WeEygkWqeWAdnwRUKtH5SiHFkSUlMLsQhW7FQ04OwIMt3HR60QrnqNE+k5jc+3vXsIKNbKRE3nvR/EDfR684U+1Q6Grdg5ChFc5R+LBpOr6YlwqMquVd1ACt76Y2ZagmbQKxpdoIkeS/0TS1R3flErWKDOQnm0RxE/pXu6k=,iv:4J+I1/PNJ4z1l+iss1v4SR8LSc+7mh3QPAbLZePyXZg=,tag:jlaf8ua/wfJNMMvS2wgmFA==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.9.1
