#ENC[AES256_GCM,data:DB1rMDdnTqRa/qhcsHeLAwSEgMzcQauzgh9mp/XEEmzWVeSf9o0VNcq8Xjx67XXIiA==,iv:6e5X3gj/hMADVUDBzrtUIX0o83EQKI8ss9rMqS7yaxo=,tag:LH8tyH2hpEuDyWaX4o5HTw==,type:comment]
#ENC[AES256_GCM,data:e0DNAUMHPQHkxoY=,iv:D1G2JeI3H6ZzCcghKqwOE8DbKhemRA7XztLrX7Vr4iU=,tag:bMyP1cnFjygrtxmgZLKP2g==,type:comment]
DB_PASSWORD: ENC[AES256_GCM,data:k60pzBaMRz4n3BCa4NJqPg4yIa+s5cwasHrz2q8t4vk=,iv:w0i/O86GDUOzAKABj6PZek3s/yvopmlyfIxlJWGpYys=,tag:Oq1AtkhhjyiLfyIN0NmlEg==,type:str]
DB_NAME: ENC[AES256_GCM,data:Cv73NamzpOSi3ZMJx7QrXVXH9yw=,iv:RmZcXLSo3zrDxZ6GXPB1DyCauQkFYt8pUO20/Fc6wFs=,tag:Vi+wh2LSi2hTBtmJ+X6NbA==,type:str]
DATABASE_URL: ENC[AES256_GCM,data:G01pg+B5spV6AsebQ+QRG51o+2CyMQxK4WEIE6vDfVH0zfYEUX8OFFu6W4hytY9H1eVgvmqNeHDBAOo9k+kgLED53RrHPQHJeC5J0/6rj53UMQyi2XAS3vI=,iv:/ZAchN/XZjm2mfI7FpA6tLjrBBVuVy54H+EqkeIWbyc=,tag:vX2cTH7ExrEAccfruZkFrQ==,type:str]
#ENC[AES256_GCM,data:F/XCF2Wt,iv:rKF2k8QJHjCa7N6CzgGMQTpniufB6WJtSgZqpBYvAPM=,tag:lvEereqPU4x2Q56m6PJk/w==,type:comment]
REDIS_PASSWORD: ENC[AES256_GCM,data:wmeFK1hmT1z+ac6ek8H3ScKXGzFVK+6B2IEI4WQ=,iv:WdZNql7HvfEnifcra6iJG4hDvfXhF/2ylJfGXY/1k7E=,tag:f3zkCl7a1lU5GLz8R7ntfw==,type:str]
REDIS_URL: ENC[AES256_GCM,data:oBjrJVp66IdJfZJacV0EzodD,iv:irnnJ5ITdP1yi1EdiXPuM851/rCNMd82vF03m7G9Lb4=,tag:RZDxa9HTRp08UFPKLnk3wg==,type:str]
#ENC[AES256_GCM,data:ObrsSXTUttqWrQV2qQ==,iv:ToiFhYgNBd1ifcraWL3YuPNyTWi4Sa0WaQv7/XpzIe0=,tag:QquEcXhveecjw4uu6LJnsw==,type:comment]
JWT_SECRET: ENC[AES256_GCM,data:15LIQta5Hk+AR/HdCRzRtVsa6+f4Z/eVYWwWtdL8YCowWxLflUA=,iv:W8+CCUM+yhaN1r00faWhabOmF0zdaM+5rwuDsr8NdCo=,tag:Pvo7pPTM3SwFfrhFL7xG4Q==,type:str]
REFRESH_TOKEN_SECRET: ENC[AES256_GCM,data:Ha4vTm8R2bAKEgLc2jdEGb2NcZPL7oYr9XBwguWqKwbnvKDX9/kjjzWR,iv:+p/Un3vsqSxABOgETr21Xyb26VxOscKRCED3EqgBJO0=,tag:dF/dZzfhDHheOKvWi28wvQ==,type:str]
INTERNAL_API_KEY: ENC[AES256_GCM,data:T20ep5Ko3aWqJsTy/echJ/gAl0yV2GP0nZVy0Ggg+A==,iv:jgzprAkUG7CdUVkgbTnWcw/xU1uvN+yp+C/fGeTPRD4=,tag:HtiV8LKiTS6lyd5KNta0aw==,type:str]
NEXTAUTH_SECRET: ENC[AES256_GCM,data:gtSmO5qQhaFs46ImN1MX2X9IpJCp7IUR02xsuoD4,iv:txO+jJSH+SeqT1TQ0l+JwZeBD5YP0OYyUhBFBebAKCU=,tag:NMeYMM+AuuO8lwZKJZ3MBg==,type:str]
#ENC[AES256_GCM,data:C17sUjLW9od8sqRv,iv:tATLqbACyb9e2ZQrYYhqUnzjUoDct8MQDUulEbqlm9o=,tag:LsGVOw9xa9wEBGeZ9bxKSw==,type:comment]
S3_ACCESS_KEY: ENC[AES256_GCM,data:9i82VhHvGX1xJQvaBa7AQe3e93xI69fw+YdXjA==,iv:wdCbe9CwbhStTlmMIQctRFtRyJ8UVAKx5FRw/zOH8wI=,tag:EJMe35A2dGcDhFN4OsoHRA==,type:str]
S3_SECRET_KEY: ENC[AES256_GCM,data:TG35JVQFkCUAXvv+IiWAZ454M1fmR3Nx9lJb6Q==,iv:nofuxBPQ5sQW9WYD8MfLTLx1/y4k5ViwtSgmbGiGcbA=,tag:tpYQ4nbm/EpiI4hZbmziHQ==,type:str]
S3_BUCKET: ENC[AES256_GCM,data:VHWfsUfLlcR1XbIIe0NF,iv:P8Wyy64V0FTpjyQDhDRoYvgzlZJ/QNA+LObpvjl4E90=,tag:IJYlhkr68i1RReyQHPe0xw==,type:str]
#ENC[AES256_GCM,data:p8Tt5o8tVUzsT2CTXQ==,iv:sO0fEMOl5ukikJIYStdnMny7HcFafDWyeXc04Pu9JeA=,tag:1EJH1DPCUsC0c9tVKRe6hA==,type:comment]
GRAFANA_ADMIN_PASSWORD: ENC[AES256_GCM,data:goaCOPUT88ITLpje7JbyIo8Y6od28q6I9XYTSL2HtP4=,iv:KI3I7KRpfI1u1Aa9sTi6q6lMNioavq8gSH0yOjs1BVE=,tag:jN4zmoY9qXHh6k0dnVqIPA==,type:str]
#ENC[AES256_GCM,data:/znspPw=,iv:AqQslDiOs1jUBdwjA06NqgZ8+v4CbmLDg3ETzgbddm8=,tag:kSI0Rb1L0PiuvoTjIa72JQ==,type:comment]
SMTP_HOST: ENC[AES256_GCM,data:0Jh8N+AmnWfXFbHdzZv3gQ==,iv:8U3/wC0eX0wpWm4HmMrlCmARI1W1v5a6yne7UuWi2m4=,tag:bqWBj/ncAx7OKW+PnKCGdg==,type:str]
SMTP_USER: ENC[AES256_GCM,data:Rf5ZGx3XA7KHjntGln2+JuJZBA==,iv:kpRYeeCUWlkAExv1QHSRtEOj2ouzCJs0b++mstMgb9Y=,tag:EuA/+DHNXGFJbsTRpLfbVg==,type:str]
SMTP_PASSWORD: ENC[AES256_GCM,data:TZQj5dexDOnGkQfq5A7Tex46uPqmp2c=,iv:jFk/7yXTe8XnoEqnc/9dSTYWzJLXKDDKZO04zZFuIdw=,tag:PkvO9fSLsVqGncch3h1hFg==,type:str]
SMTP_FROM: ENC[AES256_GCM,data:f78vMSrRS0WqsmNdJBqf3wUnfA==,iv:IM6/TSjVm5FPE/mCJjgyVSVwnZhWd6KX9lOL76zfxAw=,tag:0tITa4j1FjwhPa5uROc9+A==,type:str]
#ENC[AES256_GCM,data:J5eRTRks8hahX2F6gBs=,iv:AqfyuUUV0SIhbrcDUEZgoalj6yLfVKuDGRzmctT2AD4=,tag:Ned7ouXhl8oc8y30/7IAXA==,type:comment]
FRONTEND_URL: ENC[AES256_GCM,data:8GWmQWwtDEXOT+1odLTLtJbqGw==,iv:+vACXS7vifyYSv1gJCQQ7agMTOT/T7yWjFppkODdWcI=,tag:niQ3YlE00vF3ZIZmp4KnHA==,type:str]
LOG_LEVEL: ENC[AES256_GCM,data:R7ix8g==,iv:KZZ+RtIoP+CUxe8vDx0dExxYzXIdThlqr4Bw3nk++FE=,tag:AzR4swn0gcbbZs81muDbAw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1ts2rpha0f7rjlslevf62t604q2gh7s68mt90h6lg70250pr4w59qzzk5tc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFNnd5YUxXWGw1WCtsak1D
        QmxrZm5RSVZjVENoMXFXOTlRa2hQVjRUaDBzCnpaKy9TV2dLOFVTNUhuYWdhcVRR
        MmVsT2s0NEZXTlJnYXlCdFdkejRvTEEKLS0tICt5WS8zaFVaSG5xdnNYc2kyejNE
        clQ4ZzA4dHIvUVE4VUNyUDZtREFMRTgKTdpitQ2Ngfla/N/T9dPr4pNq0YowpPhr
        uNdmGrQ71zdO/Qr0LLAf3rS7z5+MhJrw/RrIx2TO7q2hWaLCEDKOkA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: '2026-04-15T07:52:52Z'
  mac: ENC[AES256_GCM,data:+WcK9sM4e4mGDAnkyOMQ/G8mcGT0vYTk40cWi5vyZUPTRMw0cact6r3cQ6AcSi52rHz0jHrA2sceWtCxshktJ08KGRyrCVdKEcp2BjahlONJyqrUypqeE+D9VG5Vo6oFWKSBRqJGVjK0V6TNFMXGCwFq2D2QI2KCJR4qaamRH3s=,iv:sJ9EvdH904pTmYA9w9pgrviXxg/8iX6695AytwUJB0Y=,tag:SonAA9dIP1hw+0SQSIHsEw==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.9.1
