CREATE INDEX "cable_loss_measurements_measured_by_idx" ON "cable_loss_measurements" USING btree ("measured_by");--> statement-breakpoint
CREATE INDEX "cable_loss_measurements_measurement_equipment_id_idx" ON "cable_loss_measurements" USING btree ("measurement_equipment_id");--> statement-breakpoint
CREATE INDEX "documents_uploaded_by_idx" ON "documents" USING btree ("uploaded_by");--> statement-breakpoint
CREATE INDEX "equipment_imports_approver_id_idx" ON "equipment_imports" USING btree ("approver_id");--> statement-breakpoint
CREATE INDEX "equipment_imports_received_by_idx" ON "equipment_imports" USING btree ("received_by");--> statement-breakpoint
CREATE INDEX "equipment_imports_equipment_id_idx" ON "equipment_imports" USING btree ("equipment_id");--> statement-breakpoint
CREATE INDEX "equipment_imports_return_checkout_id_idx" ON "equipment_imports" USING btree ("return_checkout_id");--> statement-breakpoint
CREATE INDEX "incident_history_reported_by_idx" ON "equipment_incident_history" USING btree ("reported_by");--> statement-breakpoint
CREATE INDEX "equipment_location_history_changed_by_idx" ON "equipment_location_history" USING btree ("changed_by");--> statement-breakpoint
CREATE INDEX "maintenance_history_performed_by_idx" ON "equipment_maintenance_history" USING btree ("performed_by");--> statement-breakpoint
CREATE INDEX "self_inspections_confirmed_by_idx" ON "equipment_self_inspections" USING btree ("confirmed_by");--> statement-breakpoint
CREATE INDEX "form_template_revisions_revised_by_idx" ON "form_template_revisions" USING btree ("revised_by");--> statement-breakpoint
CREATE INDEX "form_templates_uploaded_by_idx" ON "form_templates" USING btree ("uploaded_by");--> statement-breakpoint
CREATE INDEX "teams_leader_id_idx" ON "teams" USING btree ("leader_id");--> statement-breakpoint
CREATE INDEX "test_software_primary_manager_id_idx" ON "test_software" USING btree ("primary_manager_id");--> statement-breakpoint
CREATE INDEX "test_software_secondary_manager_id_idx" ON "test_software" USING btree ("secondary_manager_id");--> statement-breakpoint
CREATE INDEX "test_software_created_by_idx" ON "test_software" USING btree ("created_by");--> statement-breakpoint
CREATE INDEX "software_validations_received_by_idx" ON "software_validations" USING btree ("received_by");--> statement-breakpoint
CREATE INDEX "software_validations_performed_by_idx" ON "software_validations" USING btree ("performed_by");--> statement-breakpoint
CREATE INDEX "software_validations_submitted_by_idx" ON "software_validations" USING btree ("submitted_by");--> statement-breakpoint
CREATE INDEX "software_validations_technical_approver_id_idx" ON "software_validations" USING btree ("technical_approver_id");--> statement-breakpoint
CREATE INDEX "software_validations_quality_approver_id_idx" ON "software_validations" USING btree ("quality_approver_id");--> statement-breakpoint
CREATE INDEX "software_validations_rejected_by_idx" ON "software_validations" USING btree ("rejected_by");--> statement-breakpoint
CREATE INDEX "software_validations_created_by_idx" ON "software_validations" USING btree ("created_by");--> statement-breakpoint
CREATE INDEX "idx_system_settings_updated_by" ON "system_settings" USING btree ("updated_by");--> statement-breakpoint
CREATE INDEX "intermediate_inspections_submitted_by_idx" ON "intermediate_inspections" USING btree ("submitted_by");--> statement-breakpoint
CREATE INDEX "intermediate_inspections_reviewed_by_idx" ON "intermediate_inspections" USING btree ("reviewed_by");--> statement-breakpoint
CREATE INDEX "intermediate_inspections_approved_by_idx" ON "intermediate_inspections" USING btree ("approved_by");--> statement-breakpoint
CREATE INDEX "intermediate_inspections_rejected_by_idx" ON "intermediate_inspections" USING btree ("rejected_by");--> statement-breakpoint
CREATE INDEX "irs_document_id_idx" ON "inspection_result_sections" USING btree ("document_id");--> statement-breakpoint
CREATE INDEX "irs_created_by_idx" ON "inspection_result_sections" USING btree ("created_by");--> statement-breakpoint
CREATE INDEX "irs_updated_by_idx" ON "inspection_result_sections" USING btree ("updated_by");