http.host: "0.0.0.0"
xpack.monitoring.elasticsearch.hosts: [ "http://elasticsearch:9200" ]

# X-Pack monitoring
xpack.monitoring.enabled: true
xpack.monitoring.elasticsearch.username: elastic
xpack.monitoring.elasticsearch.password: changeme

# Pipeline configuration
path.config: /usr/share/logstash/pipeline

# Allow dynamic reload
config.reload.automatic: true
config.reload.interval: 3s 