# Generated by Django 5.1.7 on 2025-03-10 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=[('available', '사용 가능'), ('borrowed', '대여 중'), ('checked_out', '반출 중'), ('calibration_soon', '교정 예정'), ('calibration_overdue', '교정 기한 초과')], default='available', max_length=20, verbose_name='상태'),
        ),
    ]
