# Generated by Django 5.1.7 on 2025-03-10 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_alter_equipment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='management_method',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
