# Generated by Django 5.1.7 on 2025-03-10 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_equipment_management_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='management_method',
            field=models.CharField(choices=[('external_calibration', '외부교정'), ('self_check', '자체점검'), ('not_applicable', '비대상')], default='external_calibration', max_length=100, verbose_name='관리방법'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='purchase_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='구입년도'),
        ),
    ]
