# Generated by Django 5.1.7 on 2025-03-10 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_alter_equipment_management_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='management_method',
            field=models.CharField(blank=True, choices=[('external_calibration', '외부교정'), ('self_check', '자체점검'), ('not_applicable', '비대상')], default='external_calibration', max_length=100, verbose_name='관리방법'),
        ),
    ]
