# Generated by Django 5.1.7 on 2025-03-11 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0005_alter_equipment_management_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calibrationhistory',
            name='institution',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='calibrationhistory',
            name='result',
            field=models.CharField(max_length=255),
        ),
    ]
