# Generated by Django 5.1.7 on 2025-03-11 00:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0006_alter_calibrationhistory_institution_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmentlocationhistory',
            options={'ordering': ['-change_date'], 'verbose_name': '위치 변동 이력', 'verbose_name_plural': '위치 변동 이력'},
        ),
        migrations.AlterField(
            model_name='equipmentlocationhistory',
            name='change_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='변동일시'),
        ),
        migrations.AlterField(
            model_name='equipmentlocationhistory',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_history', to='equipment.equipment', verbose_name='장비'),
        ),
        migrations.AlterField(
            model_name='equipmentlocationhistory',
            name='location',
            field=models.CharField(max_length=100, verbose_name='위치'),
        ),
        migrations.AlterField(
            model_name='equipmentlocationhistory',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='비고'),
        ),
    ]
