# Generated by Django 5.1.7 on 2025-03-11 01:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0007_alter_equipmentlocationhistory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentlocationhistory',
            name='change_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='변동일시'),
        ),
    ]
