# Generated by Django 5.1.7 on 2025-03-11 01:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0008_alter_equipmentlocationhistory_change_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField(default=django.utils.timezone.now, verbose_name='발생 일시')),
                ('issue_type', models.CharField(choices=[('damage', '손상'), ('malfunction', '오작동'), ('modification', '변경'), ('repair', '수리')], max_length=20, verbose_name='유형')),
                ('description', models.TextField(verbose_name='주요 내용')),
                ('resolved', models.BooleanField(default=False, verbose_name='해결 여부')),
                ('resolved_date', models.DateField(blank=True, null=True, verbose_name='해결 일시')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_history', to='equipment.equipment', verbose_name='장비')),
            ],
            options={
                'verbose_name': '장비 문제 내역',
                'verbose_name_plural': '장비 문제 내역',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_date', models.DateField(default=django.utils.timezone.now, verbose_name='유지보수 일시')),
                ('description', models.TextField(verbose_name='주요 내용')),
                ('performed_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='수행자')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_history', to='equipment.equipment', verbose_name='장비')),
            ],
            options={
                'verbose_name': '장비 유지보수 내역',
                'verbose_name_plural': '장비 유지보수 내역',
                'ordering': ['-maintenance_date'],
            },
        ),
    ]
