# Generated by Django 5.1.7 on 2025-03-18 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0013_maintenancehistory_repairhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='accessories',
            field=models.TextField(blank=True, null=True, verbose_name='부속품 목록'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='firmware_version',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='펌웨어 버전'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='installation_date',
            field=models.DateField(blank=True, null=True, verbose_name='설치 일시'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='key_features',
            field=models.TextField(blank=True, null=True, verbose_name='주요 기능'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='manual_location',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='메뉴얼 보관 위치'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='manufacturer_contact',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='제조사 연락처'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='needs_calibration',
            field=models.BooleanField(default=False, verbose_name='교정 필요'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='primary_technical_manager',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='기술책임자(정)'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='secondary_technical_manager',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='기술책임자(부)'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='software_version',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='S/W 버전'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='specification_compliance',
            field=models.BooleanField(default=False, verbose_name='시방 일치'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='supplier',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='공급사'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='supplier_contact',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='공급사 연락처'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=[('available', '사용 가능'), ('borrowed', '대여 중'), ('checked_out', '반출 중'), ('calibration_soon', '교정 예정'), ('calibration_overdue', '교정 기한 초과'), ('spare', '여분')], default='available', max_length=20, verbose_name='상태'),
        ),
    ]
