# Generated by Django 5.1.7 on 2025-03-18 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0014_equipment_accessories_equipment_firmware_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='equipment_images/', verbose_name='장비 이미지'),
        ),
    ]
