# Generated by Django 5.1.7 on 2025-03-18 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0015_equipment_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentloan',
            name='borrowed_date',
            field=models.DateField(blank=True, null=True, verbose_name='대여일'),
        ),
    ]
