# Generated by Django 5.1.7 on 2025-03-18 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0016_equipmentloan_borrowed_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='borrowed_date',
            field=models.DateField(blank=True, null=True, verbose_name='대여일'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='borrower',
            field=models.IntegerField(blank=True, null=True, verbose_name='대여자 ID'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='borrower_department',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='대여자 부서'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='borrower_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='대여자 이름'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='expected_return_date',
            field=models.DateField(blank=True, null=True, verbose_name='반납 예정일'),
        ),
    ]
