# Generated by Django 5.1.7 on 2025-03-18 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0017_equipment_borrowed_date_equipment_borrower_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='team',
            field=models.CharField(choices=[('RF', 'RF팀'), ('SAR', 'SAR팀')], default='RF', max_length=10, verbose_name='소속팀'),
        ),
    ]
