# Generated by Django 5.1.7 on 2025-03-18 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0018_equipment_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='team',
            field=models.CharField(choices=[('RF', 'RF팀'), ('SAR', 'SAR팀'), ('EMC', 'EMC팀'), ('AUTO', 'Automotive팀')], default='RF', max_length=10, verbose_name='소속팀'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='team',
            field=models.CharField(choices=[('RF', 'RF팀'), ('SAR', 'SAR팀'), ('EMC', 'EMC팀'), ('AUTO', 'Automotive팀')], default='RF', max_length=10, verbose_name='소속팀'),
        ),
    ]
