/**
 * Calibration Factors seed data
 * 12 factors with various types and approval statuses
 */

import { calibrationFactors } from '@equipment-management/db/schema';
import { daysAgo, monthsAgo, monthsLater, toDateString } from '../../utils/date-helpers';
import {
  EQUIP_ANTENNA_1_SUW_E_ID,
  EQUIP_NETWORK_ANALYZER_SUW_E_ID,
  EQUIP_FILTER_SUW_E_ID,
  EQUIP_EMC_RECEIVER_SUW_E_ID,
  EQUIP_OSCILLOSCOPE_SUW_R_ID,
  EQUIP_SAR_PROBE_SUW_S_ID,
  EQUIP_MEASUREMENT_STAND_SUW_S_ID,
  EQUIP_CURRENT_PROBE_SUW_A_ID,
  EQUIP_HARNESS_COUPLER_SUW_A_ID,
  EQUIP_TRANSMITTER_UIW_W_ID,
  EQUIP_RECEIVER_UIW_W_ID,
  EQUIP_AMPLIFIER_UIW_W_ID,
  USER_TEST_ENGINEER_SUWON_ID,
  USER_TECHNICAL_MANAGER_SUWON_ID,
} from '../../utils/uuid-constants';

export const CALIBRATION_FACTORS_SEED_DATA: (typeof calibrationFactors.$inferInsert)[] = [
  // Antenna Gain factors (4)
  {
    equipmentId: EQUIP_ANTENNA_1_SUW_E_ID,
    factorType: 'antenna_gain',
    factorName: '3GHz 혼 안테나 이득',
    factorValue: '15.2',
    unit: 'dBi',
    parameters: {
      frequencies: ['2.8GHz', '3.0GHz', '3.2GHz'],
      gains: [14.8, 15.2, 15.6],
      polarization: 'vertical',
    },
    effectiveDate: toDateString(monthsAgo(12)),
    expiryDate: toDateString(monthsLater(12)),
    approvalStatus: 'approved',
    requestedBy: USER_TEST_ENGINEER_SUWON_ID,
    approvedBy: USER_TECHNICAL_MANAGER_SUWON_ID,
    approverComment: '안테나 이득 정상 확인',
    createdAt: monthsAgo(12),
    updatedAt: monthsAgo(12),
  },

  {
    equipmentId: EQUIP_NETWORK_ANALYZER_SUW_E_ID,
    factorType: 'antenna_gain',
    factorName: 'Log 주기 안테나 이득 (100MHz-1GHz)',
    factorValue: '12.5',
    unit: 'dBi',
    parameters: {
      frequencyRange: '100MHz-1GHz',
      temperature: '25°C',
      humidity: '50%',
    },
    effectiveDate: toDateString(monthsAgo(6)),
    expiryDate: toDateString(monthsLater(6)),
    approvalStatus: 'approved',
    requestedBy: USER_TEST_ENGINEER_SUWON_ID,
    approvedBy: USER_TECHNICAL_MANAGER_SUWON_ID,
    approverComment: '검수 완료',
    createdAt: monthsAgo(6),
    updatedAt: monthsAgo(6),
  },

  {
    equipmentId: EQUIP_TRANSMITTER_UIW_W_ID,
    factorType: 'antenna_gain',
    factorName: '송신기 패치 안테나 이득',
    factorValue: '8.3',
    unit: 'dBi',
    parameters: {
      frequency: '2.45GHz',
      bandwidth: '100MHz',
    },
    effectiveDate: toDateString(monthsAgo(3)),
    expiryDate: toDateString(monthsLater(9)),
    approvalStatus: 'pending',
    requestedBy: USER_TEST_ENGINEER_SUWON_ID,
    approvedBy: null,
    createdAt: monthsAgo(3),
    updatedAt: daysAgo(5),
  },

  {
    equipmentId: EQUIP_RECEIVER_UIW_W_ID,
    factorType: 'antenna_gain',
    factorName: '수신기 어레이 안테나 이득',
    factorValue: '18.7',
    unit: 'dBi',
    parameters: {
      elements: 8,
      elementGain: 6.2,
      arrayGain: 18.7,
    },
    effectiveDate: toDateString(daysAgo(90)),
    expiryDate: toDateString(monthsLater(12)),
    approvalStatus: 'approved',
    requestedBy: USER_TEST_ENGINEER_SUWON_ID,
    approvedBy: USER_TECHNICAL_MANAGER_SUWON_ID,
    createdAt: monthsAgo(3),
    updatedAt: monthsAgo(3),
  },

  // Cable Loss factors (3)
  {
    equipmentId: EQUIP_EMC_RECEIVER_SUW_E_ID,
    factorType: 'cable_loss',
    factorName: 'LMR-400 동축 케이블 손실 (10m)',
    factorValue: '0.45',
    unit: 'dB',
    parameters: {
      cableType: 'LMR-400',
      length: '10m',
      frequency: '2.4GHz',
      temperature: '25°C',
    },
    effectiveDate: toDateString(monthsAgo(12)),
    expiryDate: toDateString(monthsLater(12)),
    approvalStatus: 'approved',
    requestedBy: USER_TEST_ENGINEER_SUWON_ID,
    approvedBy: USER_TECHNICAL_MANAGER_SUWON_ID,
    createdAt: monthsAgo(12),
    updatedAt: monthsAgo(12),
  },

  {
    equipmentId: EQUIP_FILTER_SUW_E_ID,
    factorType: 'cable_loss',
    factorName: 'SMA 연결 케이블 손실',
    factorValue: '0.08',
    unit: 'dB',
    parameters: {
      connectorType: 'SMA',
      length: '1m',
      frequency: '6GHz',
    },
    effectiveDate: toDateString(monthsAgo(6)),
    expiryDate: toDateString(monthsLater(6)),
    approvalStatus: 'rejected',
    requestedBy: USER_TEST_ENGINEER_SUWON_ID,
    approvedBy: USER_TECHNICAL_MANAGER_SUWON_ID,
    approverComment: '측정 오류 의심, 재측정 필요',
    createdAt: monthsAgo(6),
    updatedAt: monthsAgo(5),
  },

  {
    equipmentId: EQUIP_SAR_PROBE_SUW_S_ID,
    factorType: 'cable_loss',
    factorName: 'SAR 프로브 연결 케이블 손실',
    factorValue: '0.12',
    unit: 'dB',
    parameters: {
      probeFrequency: '900MHz-6GHz',
      length: '3m',
    },
    effectiveDate: toDateString(daysAgo(60)),
    expiryDate: toDateString(monthsLater(12)),
    approvalStatus: 'approved',
    requestedBy: USER_TEST_ENGINEER_SUWON_ID,
    approvedBy: USER_TECHNICAL_MANAGER_SUWON_ID,
    createdAt: monthsAgo(2),
    updatedAt: monthsAgo(2),
  },

  // Path Loss factors (2)
  {
    equipmentId: EQUIP_MEASUREMENT_STAND_SUW_S_ID,
    factorType: 'path_loss',
    factorName: '측정실 경로 손실 (TX-RX 거리 3m)',
    factorValue: '-45.2',
    unit: 'dB',
    parameters: {
      txRxDistance: '3m',
      frequency: '2.45GHz',
      environment: '반무향실',
      reflectionLoss: -2.5,
    },
    effectiveDate: toDateString(monthsAgo(9)),
    expiryDate: toDateString(monthsLater(3)),
    approvalStatus: 'pending',
    requestedBy: USER_TEST_ENGINEER_SUWON_ID,
    approvedBy: null,
    createdAt: daysAgo(15),
    updatedAt: daysAgo(10),
  },

  {
    equipmentId: EQUIP_AMPLIFIER_UIW_W_ID,
    factorType: 'path_loss',
    factorName: '증폭기 출력 회로 경로 손실',
    factorValue: '-0.35',
    unit: 'dB',
    parameters: {
      circuitLength: '50cm',
      frequency: '5GHz',
      impedance: '50Ω',
    },
    effectiveDate: toDateString(monthsAgo(12)),
    expiryDate: toDateString(monthsLater(12)),
    approvalStatus: 'approved',
    requestedBy: USER_TEST_ENGINEER_SUWON_ID,
    approvedBy: USER_TECHNICAL_MANAGER_SUWON_ID,
    createdAt: monthsAgo(12),
    updatedAt: monthsAgo(12),
  },

  // Amplifier Gain factors (2)
  {
    equipmentId: EQUIP_CURRENT_PROBE_SUW_A_ID,
    factorType: 'amplifier_gain',
    factorName: '1GHz 프리앰프 이득',
    factorValue: '26.5',
    unit: 'dB',
    parameters: {
      frequency: '1GHz',
      inputLevel: '-10dBm',
      outputLevel: '16.5dBm',
      noiseFigure: 3.2,
    },
    effectiveDate: toDateString(monthsAgo(12)),
    expiryDate: toDateString(monthsLater(12)),
    approvalStatus: 'approved',
    requestedBy: USER_TEST_ENGINEER_SUWON_ID,
    approvedBy: USER_TECHNICAL_MANAGER_SUWON_ID,
    createdAt: monthsAgo(12),
    updatedAt: monthsAgo(12),
  },

  {
    equipmentId: EQUIP_HARNESS_COUPLER_SUW_A_ID,
    factorType: 'amplifier_gain',
    factorName: '파워 증폭기 이득',
    factorValue: '38.2',
    unit: 'dB',
    parameters: {
      frequency: '400MHz',
      inputLevel: '0dBm',
      outputLevel: '38.2dBm',
      gainFlatness: 2.1,
    },
    effectiveDate: toDateString(monthsAgo(6)),
    expiryDate: toDateString(monthsLater(6)),
    approvalStatus: 'approved',
    requestedBy: USER_TEST_ENGINEER_SUWON_ID,
    approvedBy: USER_TECHNICAL_MANAGER_SUWON_ID,
    createdAt: monthsAgo(6),
    updatedAt: monthsAgo(6),
  },

  // Other factors (1)
  {
    equipmentId: EQUIP_OSCILLOSCOPE_SUW_R_ID,
    factorType: 'other',
    factorName: '오실로스코프 시간 기준 오차',
    factorValue: '0.003',
    unit: 'ppm',
    parameters: {
      timebase: '100ns/div',
      temperature: '25°C',
      frequencyAccuracy: '±50ppm',
    },
    effectiveDate: toDateString(monthsAgo(12)),
    expiryDate: toDateString(monthsLater(12)),
    approvalStatus: 'approved',
    requestedBy: USER_TEST_ENGINEER_SUWON_ID,
    approvedBy: USER_TECHNICAL_MANAGER_SUWON_ID,
    createdAt: monthsAgo(12),
    updatedAt: monthsAgo(12),
  },
];
